name: CICD Develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
    call-CI-workflow:
        uses: ./.github/workflows/reusable-CI.yml

    call-CD-workflow:
        needs: call-CI-workflow
        permissions:
            id-token: write
            contents: read
        uses: ./.github/workflows/reusable-CD.yml
        with:
            model-serving-api-name: develop-cp-model-serving-api
            interface-name: develop-cp-interface
