name: CICD Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    call-CI-workflow:
        uses: ./.github/workflows/reusable-CI.yml

    call-CD-workflow:
        needs: call-CI-workflow
        permissions:
            id-token: write
            contents: read
        uses: ./.github/workflows/reusable-CD.yml
        with:
            model-serving-api-name: cp-model-serving-api
            interface-name: cp-interface
