name: Reusable CD Workflow

on:
    workflow_call:
        inputs:
            model-serving-api-name:
                required: true
                type: string
            interface-name:
                required: true
                type: string

env:
    MODEL_SERVING_BASE_URL: https://${{ inputs.model-serving-api-name }}-436098836644.europe-west1.run.app

jobs:
    build-and-deploy:
        permissions:
            id-token: write
            contents: read
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Google auth
              id: auth
              uses: google-github-actions/auth@v2.1.10
              with:
                create_credentials_file: true
                workload_identity_provider: projects/436098836644/locations/global/workloadIdentityPools/cloudypoints-production/providers/cloudypoints-production
                service_account: github-actions-sa@cloudypoints-452719.iam.gserviceaccount.com

            - name: Set up Google Cloud SDK
              uses: google-github-actions/setup-gcloud@v2.1.4
              with:
                project_id: cloudypoints-452719

            - name: Deploy Model Serving to Cloud
              run: |
                gcloud run deploy ${{ inputs.model-serving-api-name }} \
                --region=europe-west1 \
                --source=$(pwd) \
                --allow-unauthenticated \
                --memory=8Gi \
                --cpu=2 \
                --add-volume name=cp_volume_user_data,type=cloud-storage,bucket=cp_bucket_user_data \
                --add-volume-mount volume=cp_volume_user_data,mount-path=/mnt/user_data_storage \
                --build-service-account projects/cloudypoints-452719/serviceAccounts/github-actions-sa@cloudypoints-452719.iam.gserviceaccount.com \
                --quiet

            - name: Deploy Interface
              run: |
                gcloud run deploy ${{ inputs.interface-name }} \
                --region=europe-west1 \
                --source=$(pwd)/interface \
                --platform managed \
                --allow-unauthenticated \
                --memory=512Mi \
                --cpu=1 \
                --update-env-vars=CP_BASE_URL="${{ env.MODEL_SERVING_BASE_URL }}" \
                --build-service-account projects/cloudypoints-452719/serviceAccounts/github-actions-sa@cloudypoints-452719.iam.gserviceaccount.com \
                --service-account projects/cloudypoints-452719/serviceAccounts/streamlit-gcs-sa@cloudypoints-452719.iam.gserviceaccount.com \
                --quiet
